import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# ------------------------------------------------
# Load dataset (generated by generate_data.py)
# ------------------------------------------------

DATA_PATH = "../generated_data/campus_occupancy_dataset.csv"

df = pd.read_csv(DATA_PATH)
df.columns = df.columns.str.upper()

# ------------------------------------------------
# Feature engineering
# ------------------------------------------------

df["UTILIZATION"] = df["ACTUAL_ATTENDANCE"] / df["VENUE_CAPACITY"]
df["OVERCROWDED"] = (df["UTILIZATION"] > 1).astype(int)
df["ENROLL_PRESSURE"] = df["ENROLLED_STUDENTS"] / df["VENUE_CAPACITY"]

# ------------------------------------------------
# Create output folder
# ------------------------------------------------

os.makedirs("../reports/eda", exist_ok=True)

# ------------------------------------------------
# 1. Utilization histogram
# ------------------------------------------------

plt.figure(figsize=(8,5))
sns.histplot(df["UTILIZATION"], bins=20, kde=True)
plt.axvline(1, color="red", linestyle="--")
plt.title("Classroom Utilization Distribution")
plt.savefig("../reports/eda/utilization_hist.png")
plt.close()

# ------------------------------------------------
# 2. Venue stress heatmap
# ------------------------------------------------

venue_util = df.groupby("VENUE")["UTILIZATION"].mean()

plt.figure(figsize=(6,8))
sns.heatmap(venue_util.to_frame(), annot=True, cmap="Reds")
plt.title("Average Venue Stress Level")
plt.savefig("../reports/eda/venue_heatmap.png")
plt.close()

# ------------------------------------------------
# 3. School overcrowding risk
# ------------------------------------------------

school_risk = df.groupby("SCHOOL")["OVERCROWDED"].mean()

plt.figure(figsize=(8,5))
school_risk.sort_values().plot(kind="barh")
plt.title("Overcrowding Risk by School")
plt.savefig("../reports/eda/school_risk.png")
plt.close()

# ------------------------------------------------
# 4. Enrollment pressure
# ------------------------------------------------

plt.figure(figsize=(8,5))
sns.boxplot(x="OVERCROWDED", y="ENROLL_PRESSURE", data=df)
plt.title("Enrollment Pressure vs Overcrowding")
plt.savefig("../reports/eda/enrollment_pressure.png")
plt.close()

print("✅ EDA complete — graphs saved in reports/eda/")
